### ISSUE TITLE
KEGG2BIGG

### ISSUE THREAD

**Issue by Rotembartuv** [Ojami/BiKEGG#3]
Hi,

I'm currently working with bacteria GAMs constructed using CarvMe (that using BIGG database). I'm trying to construct a fungi GEM, and I came across Kbase, which uses the KEGG database.
I wanted to know if you have the option to convert from KEGG to BIGG (the opposite of `bigg2kegg`)

Tnx

**Comment by Ojami** [comment]
Hello there,

We're not maintaining BiKEGG toolbox anymore, however, you can use directly BiGG or metanetx for that purpose. An example with BiGG:

```
% Read from BiGG API
opts = weboptions(Timeout=5e4);
bds = readtable("http://bigg.ucsd.edu/static/namespace/bigg_models_reactions.txt", WebOptions=opts, TextType="string");

idx = bds.database_links.lower.contains("kegg"); % only rxns with available KEGG id
bds(~idx, :) = [];
bds.KEGG = regexp(bds.database_links, "(?<=/kegg.reaction/)(.*?)(?=;)", "match"); % Extract KEGG reaction IDs
```
BiKEGG was initially developed to match and reconcile rxn IDs missing from BiGG, so you may with to take look at https://www.metanetx.org/mnxdoc/mnxref.html as well. I assume metanetx covers more ID mappings than BiGG API (my example above).

Hope this helps
Cheers
Oveis

**Comment by smoretti** [comment]
@Rotembartuv Feel free to ask directly at MetaNetX help@metanetx.org
We have an ID mapper and a SPARQL endpoint to help for this kind of conversion.
